# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='levelSchema',
            fields=[
                ('id', models.AutoField(help_text='Enter the level no.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Enter the level name', max_length=100, null=True)),
                ('level_photo', models.ImageField(blank=True, null=True, upload_to='level/')),
                ('ans', models.CharField(help_text='Enter the ans of the level', max_length=200)),
                ('js', models.CharField(blank=True, help_text='Enter the js if any available for this level', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userSchema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank=True, help_text='Enter user phone number', null=True)),
                ('location', models.CharField(max_length=200)),
                ('currlevel', models.ManyToManyField(blank=True, default=1, to='obscura.levelSchema')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
