# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschema',
            name='currlevel',
        ),
        migrations.AddField(
            model_name='userschema',
            name='currlevel',
            field=models.IntegerField(default=1),
        ),
    ]
