# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0003_auto_20170603_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelschema',
            name='user',
        ),
    ]
